// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    db: {
      url: process.env.DATABASE_URL,
      provider: "mysql",
    },
  },
  warnings: {
    drift: process.env.NODE_ENV === "production" ? "error" : "warn",
  },
});
