export const MOCK_MOVIES = [
  {
    id: 1,
    title: "The Dark Knight",
    slug: "the-dark-knight",
    genre: ["Action", "Crime"],
    type: "movie",
    country: "US",
    language: "English",
    rating: 9.0,
    year: 2008,
    trending: true,
    poster:
      "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=300&h=450&fit=crop",
    quality: "4K",
  },
  {
    id: 2,
    title: "Parasite",
    slug: "parasite",
    genre: ["Drama", "Thriller"],
    type: "movie",
    country: "KR",
    language: "Korean",
    rating: 8.6,
    year: 2019,
    trending: true,
    poster:
      "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=300&h=450&fit=crop",
    quality: "HD",
  },
  {
    id: 3,
    title: "Stranger Things",
    slug: "stranger-things",
    genre: ["Sci-Fi", "Horror"],
    type: "series",
    country: "US",
    language: "English",
    rating: 8.7,
    year: 2016,
    trending: true,
    poster:
      "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=300&h=450&fit=crop",
    quality: "4K",
  },
  {
    id: 4,
    title: "Spirited Away",
    slug: "spirited-away",
    genre: ["Animation", "Fantasy"],
    type: "anime",
    country: "JP",
    language: "Japanese",
    rating: 8.6,
    year: 2001,
    trending: false,
    poster:
      "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=300&h=450&fit=crop",
    quality: "HD",
  },
  {
    id: 5,
    title: "Inception",
    slug: "inception",
    genre: ["Sci-Fi", "Action"],
    type: "movie",
    country: "US",
    language: "English",
    rating: 8.8,
    year: 2010,
    trending: false,
    poster:
      "https://images.unsplash.com/photo-1574267432644-f610a6733e3e?w=300&h=450&fit=crop",
    quality: "4K",
  },
  {
    id: 6,
    title: "Breaking Bad",
    slug: "breaking-bad",
    genre: ["Drama", "Crime"],
    type: "series",
    country: "US",
    language: "English",
    rating: 9.5,
    year: 2008,
    trending: true,
    poster:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=300&h=450&fit=crop",
    quality: "HD",
  },
  {
    id: 7,
    title: "Your Name",
    slug: "your-name",
    genre: ["Animation", "Romance"],
    type: "anime",
    country: "JP",
    language: "Japanese",
    rating: 8.4,
    year: 2016,
    trending: false,
    poster:
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop",
    quality: "HD",
  },
  {
    id: 8,
    title: "Squid Game",
    slug: "squid-game",
    genre: ["Thriller", "Drama"],
    type: "series",
    country: "KR",
    language: "Korean",
    rating: 8.0,
    year: 2021,
    trending: true,
    poster:
      "https://images.unsplash.com/photo-1574267432644-f610a6733e3e?w=300&h=450&fit=crop",
    quality: "4K",
  },
  {
    id: 9,
    title: "Avengers: Endgame",
    slug: "avengers-endgame",
    genre: ["Action", "Sci-Fi"],
    type: "movie",
    country: "US",
    language: "English",
    rating: 8.4,
    year: 2019,
    trending: false,
    poster:
      "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=300&h=450&fit=crop",
    quality: "4K",
  },
  {
    id: 10,
    title: "Demon Slayer",
    slug: "demon-slayer",
    genre: ["Animation", "Action"],
    type: "anime",
    country: "JP",
    language: "Japanese",
    rating: 8.7,
    year: 2019,
    trending: true,
    poster:
      "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=300&h=450&fit=crop",
    quality: "HD",
  },
  {
    id: 11,
    title: "The Crown",
    slug: "the-crown",
    genre: ["Drama", "History"],
    type: "series",
    country: "UK",
    language: "English",
    rating: 8.2,
    year: 2016,
    trending: false,
    poster:
      "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=300&h=450&fit=crop",
    quality: "HD",
  },
  {
    id: 12,
    title: "Interstellar",
    slug: "interstellar",
    genre: ["Sci-Fi", "Drama"],
    type: "movie",
    country: "US",
    language: "English",
    rating: 8.6,
    year: 2014,
    trending: false,
    poster:
      "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=300&h=450&fit=crop",
    quality: "4K",
  },
];
